// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    databaseURL: 'https://chatapp-8da05-default-rtdb.firebaseio.com/',
    apiKey: 'AIzaSyDcO5DMxcnefSn9XOx4q2-OHaYQNkjrxFQ',
    appId: '1:569220072785:web:5d567aaa831ed56a8abf70',
    messagingSenderId: '569220072785',
    projectId: 'chatapp-8da05',
    authDomain: 'chatapp-8da05.firebaseapp.com',
    storageBucket: 'chatapp-8da05.appspot.com',
    measurementId: 'G-Y1F60HNFV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    databaseURL: 'https://chatapp-8da05-default-rtdb.firebaseio.com/',
    apiKey: 'AIzaSyBlxO1vj_9EEJ2Zcjej78l2A5xOURImFTw',
    appId: '1:569220072785:android:868ed32a275262588abf70',
    messagingSenderId: '569220072785',
    projectId: 'chatapp-8da05',
    storageBucket: 'chatapp-8da05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    databaseURL: 'https://chatapp-8da05-default-rtdb.firebaseio.com/',
    apiKey: 'AIzaSyA646UrNtDWwTWBb48ehOKlhINokNJW_1M',
    appId: '1:569220072785:ios:b065aeeb697e03f28abf70',
    messagingSenderId: '569220072785',
    projectId: 'chatapp-8da05',
    storageBucket: 'chatapp-8da05.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    databaseURL: 'https://chatapp-8da05-default-rtdb.firebaseio.com/',
    apiKey: 'AIzaSyA646UrNtDWwTWBb48ehOKlhINokNJW_1M',
    appId: '1:569220072785:ios:43dfe0f4ee91ba9d8abf70',
    messagingSenderId: '569220072785',
    projectId: 'chatapp-8da05',
    storageBucket: 'chatapp-8da05.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
